slam_toolbox:
  ros__parameters:
    use_sim_time: false
    map_file_name: ""
    mode: "mapping"
    resolution: 0.05
    frequency: 10.0
    publish_map: true
    map_update_interval: 5.0
    laser_scan_topic: "/scan"
    base_frame: "base_link"
    odom_frame: "odom"
